export const mockedFilmography = [
  {
    title: "Hedy Lamarr, star et inventeuse de génie",
    url: "/film/fichefilm_gen_cfilm=257984.html",
  },
  { title: "That's action", url: "/film/fichefilm_gen_cfilm=194124.html" },
  {
    title: "Femmes devant le désir",
    url: "/film/fichefilm_gen_cfilm=42966.html",
  },
  {
    title: "The Story of Mankind",
    url: "/film/fichefilm_gen_cfilm=61137.html",
  },
  { title: "L'Amante di Paride", url: "/film/fichefilm_gen_cfilm=51385.html" },
  { title: "L'Eterna femmina", url: "/film/fichefilm_gen_cfilm=109957.html" },
  {
    title: "Espionne de mon coeur",
    url: "/film/fichefilm_gen_cfilm=42734.html",
  },
  {
    title: "La dame sans passeport",
    url: "/film/fichefilm_gen_cfilm=176812.html",
  },
  { title: "Terre damnée", url: "/film/fichefilm_gen_cfilm=196208.html" },
  { title: "Samson et Dalila", url: "/film/fichefilm_gen_cfilm=9288.html" },
  { title: "La Femme deshonorée", url: "/film/fichefilm_gen_cfilm=97059.html" },
  { title: "Le Démon de la chair", url: "/film/fichefilm_gen_cfilm=564.html" },
  {
    title: "Her Highness and the Bellboy",
    url: "/film/fichefilm_gen_cfilm=114697.html",
  },
  { title: "Angoisse", url: "/film/fichefilm_gen_cfilm=53027.html" },
  { title: "Les Conspirateurs", url: "/film/fichefilm_gen_cfilm=8170.html" },
  { title: "The Heavenly body", url: "/film/fichefilm_gen_cfilm=211758.html" },
  { title: "Tortilla Flat", url: "/film/fichefilm_gen_cfilm=46387.html" },
  { title: "H.M. Pulham, Esq", url: "/film/fichefilm_gen_cfilm=126014.html" },
  {
    title: "La Danseuse des Folies Ziegfeld",
    url: "/film/fichefilm_gen_cfilm=182101.html",
  },
  { title: "Camarade X", url: "/film/fichefilm_gen_cfilm=50576.html" },
  {
    title: "La Fièvre du pétrole",
    url: "/film/fichefilm_gen_cfilm=50537.html",
  },
  { title: "Casbah", url: "/film/fichefilm_gen_cfilm=36840.html" },
  { title: "Extase", url: "/film/fichefilm_gen_cfilm=2655.html" },
];

export const mockedCastings = {
  564: [
    "/personne/fichepersonne_gen_cpersonne=17775.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=466.html",
    "/personne/fichepersonne_gen_cpersonne=1706.html",
    "/personne/fichepersonne_gen_cpersonne=6807.html",
    "/personne/fichepersonne_gen_cpersonne=91649.html",
    "/personne/fichepersonne_gen_cpersonne=34949.html",
    "/personne/fichepersonne_gen_cpersonne=20788.html",
  ],
  2655: [
    "/personne/fichepersonne_gen_cpersonne=6707.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=6710.html",
    "/personne/fichepersonne_gen_cpersonne=34698.html",
  ],
  8170: [
    "/personne/fichepersonne_gen_cpersonne=16348.html",
    "/personne/fichepersonne_gen_cpersonne=1365.html",
    "/personne/fichepersonne_gen_cpersonne=3600.html",
    "/personne/fichepersonne_gen_cpersonne=6172.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=16350.html",
    "/personne/fichepersonne_gen_cpersonne=66977.html",
    "/personne/fichepersonne_gen_cpersonne=1046.html",
    "/personne/fichepersonne_gen_cpersonne=31370.html",
  ],
  9288: [
    "/personne/fichepersonne_gen_cpersonne=4910.html",
    "/personne/fichepersonne_gen_cpersonne=466.html",
    "/personne/fichepersonne_gen_cpersonne=4239.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=5992.html",
    "/personne/fichepersonne_gen_cpersonne=7317.html",
    "/personne/fichepersonne_gen_cpersonne=83136.html",
    "/personne/fichepersonne_gen_cpersonne=95172.html",
    "/personne/fichepersonne_gen_cpersonne=26257.html",
  ],
  36840: [
    "/personne/fichepersonne_gen_cpersonne=3489.html",
    "/personne/fichepersonne_gen_cpersonne=4495.html",
    "/personne/fichepersonne_gen_cpersonne=1046.html",
    "/personne/fichepersonne_gen_cpersonne=4314.html",
    "/personne/fichepersonne_gen_cpersonne=39654.html",
    "/personne/fichepersonne_gen_cpersonne=82578.html",
    "/personne/fichepersonne_gen_cpersonne=78935.html",
    "/personne/fichepersonne_gen_cpersonne=81370.html",
  ],
  42734: [
    "/personne/fichepersonne_gen_cpersonne=11148.html",
    "/personne/fichepersonne_gen_cpersonne=20325.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=6052.html",
    "/personne/fichepersonne_gen_cpersonne=2949.html",
  ],
  42966: [
    "/personne/fichepersonne_gen_cpersonne=33406.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=33284.html",
  ],
  46387: [
    "/personne/fichepersonne_gen_cpersonne=4066.html",
    "/personne/fichepersonne_gen_cpersonne=25.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=227.html",
    "/personne/fichepersonne_gen_cpersonne=2147.html",
    "/personne/fichepersonne_gen_cpersonne=272.html",
    "/personne/fichepersonne_gen_cpersonne=55236.html",
    "/personne/fichepersonne_gen_cpersonne=9656.html",
    "/personne/fichepersonne_gen_cpersonne=70425.html",
  ],
  50537: [
    "/personne/fichepersonne_gen_cpersonne=6754.html",
    "/personne/fichepersonne_gen_cpersonne=886.html",
    "/personne/fichepersonne_gen_cpersonne=25.html",
    "/personne/fichepersonne_gen_cpersonne=2000.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=704.html",
    "/personne/fichepersonne_gen_cpersonne=67433.html",
  ],
  50576: [
    "/personne/fichepersonne_gen_cpersonne=759.html",
    "/personne/fichepersonne_gen_cpersonne=886.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=2150.html",
    "/personne/fichepersonne_gen_cpersonne=1371.html",
    "/personne/fichepersonne_gen_cpersonne=82297.html",
    "/personne/fichepersonne_gen_cpersonne=7000.html",
  ],
  51385: [
    "/personne/fichepersonne_gen_cpersonne=5874.html",
    "/personne/fichepersonne_gen_cpersonne=17775.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=7292.html",
    "/personne/fichepersonne_gen_cpersonne=279.html",
    "/personne/fichepersonne_gen_cpersonne=10307.html",
    "/personne/fichepersonne_gen_cpersonne=25203.html",
    "/personne/fichepersonne_gen_cpersonne=102100.html",
    "/personne/fichepersonne_gen_cpersonne=10281.html",
  ],
  53027: [
    "/personne/fichepersonne_gen_cpersonne=2852.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=18921.html",
    "/personne/fichepersonne_gen_cpersonne=2854.html",
    "/personne/fichepersonne_gen_cpersonne=5038.html",
    "/personne/fichepersonne_gen_cpersonne=32951.html",
  ],
  61137: [
    "/personne/fichepersonne_gen_cpersonne=7679.html",
    "/personne/fichepersonne_gen_cpersonne=6564.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=1200.html",
    "/personne/fichepersonne_gen_cpersonne=1198.html",
    "/personne/fichepersonne_gen_cpersonne=1199.html",
    "/personne/fichepersonne_gen_cpersonne=5012.html",
    "/personne/fichepersonne_gen_cpersonne=1563.html",
    "/personne/fichepersonne_gen_cpersonne=1299.html",
  ],
  97059: [
    "/personne/fichepersonne_gen_cpersonne=1386.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
  ],
  109957: [
    "/personne/fichepersonne_gen_cpersonne=5874.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=10281.html",
    "/personne/fichepersonne_gen_cpersonne=137122.html",
    "/personne/fichepersonne_gen_cpersonne=142102.html",
    "/personne/fichepersonne_gen_cpersonne=20871.html",
    "/personne/fichepersonne_gen_cpersonne=25680.html",
  ],
  114697: [
    "/personne/fichepersonne_gen_cpersonne=2269.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=2006.html",
    "/personne/fichepersonne_gen_cpersonne=31911.html",
    "/personne/fichepersonne_gen_cpersonne=32951.html",
    "/personne/fichepersonne_gen_cpersonne=1563.html",
    "/personne/fichepersonne_gen_cpersonne=16637.html",
    "/personne/fichepersonne_gen_cpersonne=84064.html",
  ],
  126014: [
    "/personne/fichepersonne_gen_cpersonne=759.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=3268.html",
    "/personne/fichepersonne_gen_cpersonne=1204.html",
    "/personne/fichepersonne_gen_cpersonne=1293.html",
    "/personne/fichepersonne_gen_cpersonne=49.html",
    "/personne/fichepersonne_gen_cpersonne=95172.html",
    "/personne/fichepersonne_gen_cpersonne=3601.html",
    "/personne/fichepersonne_gen_cpersonne=101269.html",
  ],
  176812: [
    "/personne/fichepersonne_gen_cpersonne=3387.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
  ],
  182101: [
    "/personne/fichepersonne_gen_cpersonne=21951.html",
    "/personne/fichepersonne_gen_cpersonne=31992.html",
    "/personne/fichepersonne_gen_cpersonne=1963.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=7226.html",
    "/personne/fichepersonne_gen_cpersonne=7592.html",
    "/personne/fichepersonne_gen_cpersonne=2061.html",
  ],
  194124: [
    "/personne/fichepersonne_gen_cpersonne=182075.html",
    "/personne/fichepersonne_gen_cpersonne=135762.html",
  ],
  196208: [
    "/personne/fichepersonne_gen_cpersonne=13709.html",
    "/personne/fichepersonne_gen_cpersonne=1635.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=8585.html",
    "/personne/fichepersonne_gen_cpersonne=2863.html",
    "/personne/fichepersonne_gen_cpersonne=3073.html",
    "/personne/fichepersonne_gen_cpersonne=2949.html",
    "/personne/fichepersonne_gen_cpersonne=67908.html",
  ],
  211758: [
    "/personne/fichepersonne_gen_cpersonne=20324.html",
    "/personne/fichepersonne_gen_cpersonne=45.html",
    "/personne/fichepersonne_gen_cpersonne=18699.html",
    "/personne/fichepersonne_gen_cpersonne=16349.html",
    "/personne/fichepersonne_gen_cpersonne=89372.html",
    "/personne/fichepersonne_gen_cpersonne=20034.html",
    "/personne/fichepersonne_gen_cpersonne=11625.html",
    "/personne/fichepersonne_gen_cpersonne=5022.html",
  ],
  257984: ["/personne/fichepersonne_gen_cpersonne=817019.html"],
};
